name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out this form to help us diagnose and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have read the [documentation](https://mcps.readthedocs.io)
          required: false
        - label: I can reproduce this issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe the bug you encountered
      placeholder: "When I try to [action], [unexpected behavior] happens instead of [expected behavior]"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug
      placeholder: |
        1. Set up environment with...
        2. Run command...
        3. Observe error...
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "The command should successfully complete and output..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "The following error occurred..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include relevant environment details
      value: |
        - OS:
        - Python version:
        - MCPS version:
        - Relevant dependencies:
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs or Stack Trace
      description: Include any relevant error messages or stack traces
      render: python
      placeholder: "Paste error output here..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information that might help
      placeholder: "Screenshots, related issues, workarounds, etc."
    validations:
      required: false
