name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with MCPS goals
          required: false

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see added?
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation & Use Case
      description: Why is this feature important? What problem does it solve?
      placeholder: |
        This would help because:
        - It would enable...
        - Users currently have to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        The feature could work like:
        1.
        2.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other approaches?
      placeholder: "Other ways this could be implemented..."
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Example Usage
      description: How would users interact with this feature?
      render: bash
      placeholder: |
        # Example command or code snippet
        mcps --new-feature-flag ...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Related issues, discussions, or design documents
      placeholder: "See also: #123, https://..."
    validations:
      required: false

  - type: checkboxes
    id: area
    attributes:
      label: Feature Area
      options:
        - label: Data Harvesting
        - label: Analysis & Security Scanning
        - label: API / FastAPI
        - label: Web UI / Dashboard
        - label: Data Export
        - label: Documentation
        - label: Other
