"""complete_mcps_schema_with_tools_embeddings_and_processing_log

Revision ID: a924f40895c1
Revises: 92d6e346e43e
Create Date: 2025-11-19 03:48:11.458422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a924f40895c1'
down_revision: Union[str, Sequence[str], None] = '92d6e346e43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processinglog',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processinglog_status'), 'processinglog', ['status'], unique=False)
    op.create_index(op.f('ix_processinglog_url'), 'processinglog', ['url'], unique=True)
    op.create_table('server',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host_type', sa.Enum('GITHUB', 'GITLAB', 'NPM', 'PYPI', 'DOCKER', 'HTTP', name='hosttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('homepage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('readme_content', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('SAFE', 'MODERATE', 'HIGH', 'CRITICAL', 'UNKNOWN', name='risklevel'), nullable=False),
    sa.Column('verified_source', sa.Boolean(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_host_type'), 'server', ['host_type'], unique=False)
    op.create_index(op.f('ix_server_name'), 'server', ['name'], unique=False)
    op.create_index(op.f('ix_server_primary_url'), 'server', ['primary_url'], unique=True)
    op.create_index(op.f('ix_server_stars'), 'server', ['stars'], unique=False)
    op.create_index(op.f('ix_server_uuid'), 'server', ['uuid'], unique=True)
    op.create_table('contributor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('library_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_constraint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ecosystem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('RUNTIME', 'DEV', 'PEER', name='dependencytype'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_library_name'), 'dependency', ['library_name'], unique=False)
    op.create_table('prompt',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_version'), 'release', ['version'], unique=False)
    op.create_table('resourcetemplate',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('uri_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toolembedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id')
    )
    op.drop_index(op.f('ix_contributors_github_id'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_login'), table_name='contributors')
    op.drop_table('contributors')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_repo_type'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_repository_contributors_contributor_id'), table_name='repository_contributors')
    op.drop_index(op.f('ix_repository_contributors_repository_id'), table_name='repository_contributors')
    op.drop_table('repository_contributors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_contributors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('repository_id', sa.INTEGER(), nullable=False),
    sa.Column('contributor_id', sa.INTEGER(), nullable=False),
    sa.Column('contributions', sa.INTEGER(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_contributors_repository_id'), 'repository_contributors', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repository_contributors_contributor_id'), 'repository_contributors', ['contributor_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('github_id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('owner', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('homepage', sa.VARCHAR(), nullable=True),
    sa.Column('repo_type', sa.VARCHAR(), nullable=False),
    sa.Column('stars', sa.INTEGER(), nullable=False),
    sa.Column('forks', sa.INTEGER(), nullable=False),
    sa.Column('watchers', sa.INTEGER(), nullable=False),
    sa.Column('open_issues', sa.INTEGER(), nullable=False),
    sa.Column('primary_language', sa.VARCHAR(), nullable=True),
    sa.Column('topics', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('pushed_at', sa.DATETIME(), nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), nullable=False),
    sa.Column('is_fork', sa.BOOLEAN(), nullable=False),
    sa.Column('last_fetched', sa.DATETIME(), nullable=False),
    sa.Column('fetch_count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_repo_type'), 'repositories', ['repo_type'], unique=False)
    op.create_index(op.f('ix_repositories_github_id'), 'repositories', ['github_id'], unique=1)
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=False)
    op.create_table('contributors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('github_id', sa.INTEGER(), nullable=False),
    sa.Column('login', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('total_contributions', sa.INTEGER(), nullable=False),
    sa.Column('repositories_count', sa.INTEGER(), nullable=False),
    sa.Column('last_fetched', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributors_login'), 'contributors', ['login'], unique=1)
    op.create_index(op.f('ix_contributors_github_id'), 'contributors', ['github_id'], unique=1)
    op.drop_table('toolembedding')
    op.drop_table('tool')
    op.drop_table('resourcetemplate')
    op.drop_index(op.f('ix_release_version'), table_name='release')
    op.drop_table('release')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_dependency_library_name'), table_name='dependency')
    op.drop_table('dependency')
    op.drop_table('contributor')
    op.drop_index(op.f('ix_server_uuid'), table_name='server')
    op.drop_index(op.f('ix_server_stars'), table_name='server')
    op.drop_index(op.f('ix_server_primary_url'), table_name='server')
    op.drop_index(op.f('ix_server_name'), table_name='server')
    op.drop_index(op.f('ix_server_host_type'), table_name='server')
    op.drop_table('server')
    op.drop_index(op.f('ix_processinglog_url'), table_name='processinglog')
    op.drop_index(op.f('ix_processinglog_status'), table_name='processinglog')
    op.drop_table('processinglog')
    # ### end Alembic commands ###
