"""add_social_media_models

Revision ID: e7b7364b56f0
Revises: a924f40895c1
Create Date: 2025-11-19 07:49:17.684235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e7b7364b56f0'
down_revision: Union[str, Sequence[str], None] = 'a924f40895c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('platform', sa.Enum('MEDIUM', 'DEV_TO', 'HASHNODE', 'PERSONAL_BLOG', 'SUBSTACK', name='articleplatform'), nullable=False),
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('featured_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('category', sa.Enum('TUTORIAL', 'NEWS', 'DISCUSSION', 'ANNOUNCEMENT', 'QUESTION', 'SHOWCASE', 'BEST_PRACTICES', 'CASE_STUDY', 'REVIEW', 'OTHER', name='contentcategory'), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('mentioned_servers', sa.JSON(), nullable=True),
    sa.Column('mentioned_urls', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_series', sa.Boolean(), nullable=False),
    sa.Column('series_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medium_publication', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medium_claps', sa.Integer(), nullable=False),
    sa.Column('devto_reactions', sa.Integer(), nullable=False),
    sa.Column('devto_organization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('technical_depth', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_author'), 'articles', ['author'], unique=False)
    op.create_index(op.f('ix_articles_category'), 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_platform'), 'articles', ['platform'], unique=False)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_articles_quality_score'), 'articles', ['quality_score'], unique=False)
    op.create_index(op.f('ix_articles_relevance_score'), 'articles', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.create_index(op.f('ix_articles_uuid'), 'articles', ['uuid'], unique=True)
    op.create_table('companies',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('headquarters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_org', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('servers_created', sa.JSON(), nullable=True),
    sa.Column('servers_used', sa.JSON(), nullable=True),
    sa.Column('use_cases', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_type'), 'companies', ['company_type'], unique=False)
    op.create_index(op.f('ix_companies_country'), 'companies', ['country'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_uuid'), 'companies', ['uuid'], unique=True)
    op.create_index(op.f('ix_companies_website'), 'companies', ['website'], unique=False)
    op.create_table('discussions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('platform', sa.Enum('REDDIT', 'TWITTER', 'DISCORD', 'SLACK', 'HACKER_NEWS', 'STACK_OVERFLOW', name='socialplatform'), nullable=False),
    sa.Column('discussion_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discussion_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('TUTORIAL', 'NEWS', 'DISCUSSION', 'ANNOUNCEMENT', 'QUESTION', 'SHOWCASE', 'BEST_PRACTICES', 'CASE_STUDY', 'REVIEW', 'OTHER', name='contentcategory'), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('answer_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('accepted_answer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mentioned_servers', sa.JSON(), nullable=True),
    sa.Column('mentioned_urls', sa.JSON(), nullable=True),
    sa.Column('created_at_platform', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussions_author'), 'discussions', ['author'], unique=False)
    op.create_index(op.f('ix_discussions_category'), 'discussions', ['category'], unique=False)
    op.create_index(op.f('ix_discussions_created_at_platform'), 'discussions', ['created_at_platform'], unique=False)
    op.create_index(op.f('ix_discussions_discussion_id'), 'discussions', ['discussion_id'], unique=True)
    op.create_index(op.f('ix_discussions_discussion_type'), 'discussions', ['discussion_type'], unique=False)
    op.create_index(op.f('ix_discussions_platform'), 'discussions', ['platform'], unique=False)
    op.create_index(op.f('ix_discussions_quality_score'), 'discussions', ['quality_score'], unique=False)
    op.create_index(op.f('ix_discussions_relevance_score'), 'discussions', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_discussions_score'), 'discussions', ['score'], unique=False)
    op.create_index(op.f('ix_discussions_title'), 'discussions', ['title'], unique=False)
    op.create_index(op.f('ix_discussions_url'), 'discussions', ['url'], unique=False)
    op.create_index(op.f('ix_discussions_uuid'), 'discussions', ['uuid'], unique=True)
    op.create_table('events',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organizer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organizer_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attendee_count', sa.Integer(), nullable=True),
    sa.Column('rsvp_count', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('speakers', sa.JSON(), nullable=True),
    sa.Column('sponsors', sa.JSON(), nullable=True),
    sa.Column('mentioned_servers', sa.JSON(), nullable=True),
    sa.Column('recording_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slides_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('registration_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requires_registration', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_organizer'), 'events', ['organizer'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_url'), 'events', ['url'], unique=False)
    op.create_index(op.f('ix_events_uuid'), 'events', ['uuid'], unique=True)
    op.create_table('social_posts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('platform', sa.Enum('REDDIT', 'TWITTER', 'DISCORD', 'SLACK', 'HACKER_NEWS', 'STACK_OVERFLOW', name='socialplatform'), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('TUTORIAL', 'NEWS', 'DISCUSSION', 'ANNOUNCEMENT', 'QUESTION', 'SHOWCASE', 'BEST_PRACTICES', 'CASE_STUDY', 'REVIEW', 'OTHER', name='contentcategory'), nullable=True),
    sa.Column('sentiment', sa.Enum('VERY_POSITIVE', 'POSITIVE', 'NEUTRAL', 'NEGATIVE', 'VERY_NEGATIVE', name='sentimentscore'), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mentioned_servers', sa.JSON(), nullable=True),
    sa.Column('mentioned_urls', sa.JSON(), nullable=True),
    sa.Column('platform_created_at', sa.DateTime(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('subreddit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reddit_flair', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_hashtags', sa.JSON(), nullable=True),
    sa.Column('twitter_mentions', sa.JSON(), nullable=True),
    sa.Column('is_retweet', sa.Boolean(), nullable=False),
    sa.Column('retweet_count', sa.Integer(), nullable=False),
    sa.Column('discord_server', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discord_channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_author'), 'social_posts', ['author'], unique=False)
    op.create_index(op.f('ix_social_posts_category'), 'social_posts', ['category'], unique=False)
    op.create_index(op.f('ix_social_posts_platform'), 'social_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_posts_platform_created_at'), 'social_posts', ['platform_created_at'], unique=False)
    op.create_index(op.f('ix_social_posts_post_id'), 'social_posts', ['post_id'], unique=True)
    op.create_index(op.f('ix_social_posts_quality_score'), 'social_posts', ['quality_score'], unique=False)
    op.create_index(op.f('ix_social_posts_relevance_score'), 'social_posts', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_social_posts_score'), 'social_posts', ['score'], unique=False)
    op.create_index(op.f('ix_social_posts_sentiment'), 'social_posts', ['sentiment'], unique=False)
    op.create_index(op.f('ix_social_posts_subreddit'), 'social_posts', ['subreddit'], unique=False)
    op.create_index(op.f('ix_social_posts_url'), 'social_posts', ['url'], unique=False)
    op.create_index(op.f('ix_social_posts_uuid'), 'social_posts', ['uuid'], unique=True)
    op.create_table('videos',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('platform', sa.Enum('YOUTUBE', 'VIMEO', 'TWITCH', name='videoplatform'), nullable=False),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('dislike_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('TUTORIAL', 'NEWS', 'DISCUSSION', 'ANNOUNCEMENT', 'QUESTION', 'SHOWCASE', 'BEST_PRACTICES', 'CASE_STUDY', 'REVIEW', 'OTHER', name='contentcategory'), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('mentioned_servers', sa.JSON(), nullable=True),
    sa.Column('mentioned_urls', sa.JSON(), nullable=True),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_captions', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('is_unlisted', sa.Boolean(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('educational_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_category'), 'videos', ['category'], unique=False)
    op.create_index(op.f('ix_videos_channel'), 'videos', ['channel'], unique=False)
    op.create_index(op.f('ix_videos_platform'), 'videos', ['platform'], unique=False)
    op.create_index(op.f('ix_videos_published_at'), 'videos', ['published_at'], unique=False)
    op.create_index(op.f('ix_videos_quality_score'), 'videos', ['quality_score'], unique=False)
    op.create_index(op.f('ix_videos_relevance_score'), 'videos', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
    op.create_index(op.f('ix_videos_url'), 'videos', ['url'], unique=False)
    op.create_index(op.f('ix_videos_uuid'), 'videos', ['uuid'], unique=True)
    op.create_index(op.f('ix_videos_video_id'), 'videos', ['video_id'], unique=True)
    op.create_index(op.f('ix_videos_view_count'), 'videos', ['view_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_view_count'), table_name='videos')
    op.drop_index(op.f('ix_videos_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_uuid'), table_name='videos')
    op.drop_index(op.f('ix_videos_url'), table_name='videos')
    op.drop_index(op.f('ix_videos_title'), table_name='videos')
    op.drop_index(op.f('ix_videos_relevance_score'), table_name='videos')
    op.drop_index(op.f('ix_videos_quality_score'), table_name='videos')
    op.drop_index(op.f('ix_videos_published_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_platform'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel'), table_name='videos')
    op.drop_index(op.f('ix_videos_category'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_social_posts_uuid'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_url'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_subreddit'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_sentiment'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_score'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_relevance_score'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_quality_score'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_post_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform_created_at'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_category'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_author'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_events_uuid'), table_name='events')
    op.drop_index(op.f('ix_events_url'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_organizer'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_discussions_uuid'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_url'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_title'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_score'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_relevance_score'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_quality_score'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_platform'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_discussion_type'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_discussion_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_created_at_platform'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_category'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_author'), table_name='discussions')
    op.drop_table('discussions')
    op.drop_index(op.f('ix_companies_website'), table_name='companies')
    op.drop_index(op.f('ix_companies_uuid'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_country'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_type'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_articles_uuid'), table_name='articles')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_relevance_score'), table_name='articles')
    op.drop_index(op.f('ix_articles_quality_score'), table_name='articles')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_platform'), table_name='articles')
    op.drop_index(op.f('ix_articles_category'), table_name='articles')
    op.drop_index(op.f('ix_articles_author'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
